---
title: "Larval Growth"
author: "Katie McFarland"
date: "9/29/2023"
output: html_document
---

# 20231217 - started manuscript Github repostiory 'EAD-ASEB-Airradians_Larvae_crossgen_OA'
# SGurr edits
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# SET WORKING DIRECTORY 
# knitr::opts_knit$set(root.dir = "C:/Users/katherine.mcfarland/Documents/GitHub/EAD-ASEB-Airradians_multigen_OA/larvae") # Katie's
knitr::opts_knit$set(root.dir = "C:/Users/samjg/Documents/Github_repositories/EAD-ASEB-Airradians_Larvae_crossgen_OA/RAnalysis") # Sam's
```


```{r, echo=FALSE}
library(ggplot2)
library(tidyr)
library(dplyr)
library(rcompanion)
library(FSA)
library(car)
library(forcats)
library(kableExtra) # nice Rmd tables
library(emmeans)
library(ggpubr)
```


# Larval Growth Data
```{r}
df<-read.csv("Data/larval_growth.csv", header = T) %>% 
  dplyr::mutate(Lengh = as.numeric(Length)) %>% 
  
  # rename the variables for consistancy using 'case_when'
  dplyr::mutate(Parental_OA = case_when(Parental_OA ==  "LOW" ~ "Low pCO2", 
                                        Parental_OA ==  "MODERATE" ~ "Moderate pCO2", 
                                        Parental_OA ==  "HIGH" ~ "High pCO2",
                                        Parental_OA ==  "WILD" ~ "None")) %>% 
  dplyr::mutate(treatment = case_when(treatment ==  "Low OA" ~ "Low pCO2", 
                                      treatment ==  "Moderate OA" ~ "Moderate pCO2", 
                                      treatment ==  "High OA" ~ "High pCO2")) %>% 
  
  # change the levels for order when plotting - call as factors too!
  dplyr::mutate(Parental_OA = as.factor(forcats::fct_relevel(Parental_OA, c("Low pCO2", "Moderate pCO2", "High pCO2")))) %>% 
  dplyr::mutate(treatment = as.factor(forcats::fct_relevel(treatment, c("Low pCO2", "Moderate pCO2", "High pCO2")))) %>% 
  
  # rename them
  dplyr::rename(Parent_pCO2 = Parental_OA) %>% 
  dplyr::rename(Larvae_pCO2  = treatment) # done 


head(df)
str(df)
```



```{r about data}

# number of runs 
unique(df$Generation) # 1 and 2 

Rep_Summary_all <- df %>% dplyr::select(c(Generation, Age, Parent_pCO2, Larvae_pCO2)) %>% 
                       dplyr::group_by_all() %>% 
                       dplyr::summarise(n=n())

# print the runs
# summary: 

Rep_Summary_G1 <- Rep_Summary_all %>%  dplyr::filter(Generation %in% 1) # for the other paper - full grow out multigenerational
Rep_Summary_G1 %>%  kbl() %>% kable_classic(full_width = F, html_font = "Cambria")

Rep_Summary_G2 <- Rep_Summary_all %>%  dplyr::filter(Generation %in% 2) # for the other paper - full grow out multigenerational
Rep_Summary_G2 %>%  kbl() %>% kable_classic(full_width = F, html_font = "Cambria")

```


```{r}
df$treatment <- factor(df$treatment,levels = c("Low OA", "Moderate OA", "High OA"))

df$Parental_OA <- factor(df$Parental_OA,levels = c("Wild", "LOW", "MODERATE", "HIGH"))
```

### make data frames for each generation
```{r}
df_F1 <- df%>%
  filter(Generation=="1")

df_F2 <- df%>%
  filter(Generation=="2")

df_F3 <- df%>%
  filter(Generation=="3")
```


# F1 Larval Survival
```{r}

stL <- summarySE(df_F1, measurevar="Length", groupvars=c("Age", "Larvae_pCO2"))
stL 

ggplot(stL, aes(x=Age, y=Length, color=Larvae_pCO2))+ geom_line()+
  geom_point()+ 
   geom_errorbar(aes(ymin=Length-se, ymax=Length+se), width=.2,
                position=position_dodge(.1)) +
  scale_color_manual(values=c("green4", "darkorange1", "purple"))+
  theme(legend.position="right", legend.direction="vertical", legend.title = element_blank())+ theme_bw() + 
  labs(x="Age (days)", y="Percent Survival")+ #scale_y_continuous(breaks=seq(0,100,20))+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))
```

# F2 Larval Survival
```{r}

stL <- summarySE(df_F2, measurevar="Length", groupvars=c("Age", "Larvae_pCO2"))
stL 

ggplot(stL, aes(x=Age, y=Length, color=Larvae_pCO2))+ geom_line()+
  geom_point()+ 
   geom_errorbar(aes(ymin=Length-se, ymax=Length+se), width=.2,
                position=position_dodge(.1)) +
  scale_color_manual(values=c("green4", "darkorange1", "purple"))+
  theme(legend.position="right", legend.direction="vertical", legend.title = element_blank())+ theme_bw() + 
  labs(x="Age (days)", y="Percent Survival")+ #scale_y_continuous(breaks=seq(0,100,20))+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))
 
```
# F3 Larval Survival
```{r}

stL <- summarySE(df_F3, measurevar="Length", groupvars=c("Age", "Larvae_pCO2"))
stL 

ggplot(stL, aes(x=Age, y=Length, color=Larvae_pCO2))+ geom_line()+
  geom_point()+ 
   geom_errorbar(aes(ymin=Length-se, ymax=Length+se), width=.2,
                position=position_dodge(.1)) +
  scale_color_manual(values=c("green4", "darkorange1", "purple"))+
  theme(legend.position="right", legend.direction="vertical", legend.title = element_blank())+ theme_bw() + 
  labs(x="Age (days)", y="Percent Survival")+ #scale_y_continuous(breaks=seq(0,100,20))+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  facet_wrap("Parent_pCO2")
 
```


# Stats
Lenght data do not meet the assumptions of noramlity 
```{r}
leveneTest(Length ~ Larvae_pCO2, data=df_F1)
shapiro.test(df_F1$Length)

leveneTest(Length ~ Larvae_pCO2, data=df_F2)
shapiro.test(df_F2$Length)

#leveneTest(Length ~ Larvae_pCO2, data=df_F3)
#shapiro.test(df_F3$Length)
```



