---
title: "Larval Growth and Survival"
author: "Katie McFarland"
date: "9/29/2023"
output: html_document
---

# 20231217 - started manuscript Github repostiory 'EAD-ASEB-Airradians_Larvae_crossgen_OA'
# SGurr edits
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# SET WORKING DIRECTORY 
# knitr::opts_knit$set(root.dir = "C:/Users/katherine.mcfarland/Documents/GitHub/EAD-ASEB-Airradians_multigen_OA/larvae") # Katie's
knitr::opts_knit$set(root.dir = "C:/Users/samjg/Documents/Github_repositories/EAD-ASEB-Airradians_Larvae_crossgen_OA/RAnalysis") # Sam's
```


```{r, echo=FALSE}
library(ggplot2)
library(tidyr)
library(dplyr)
library(rcompanion)
library(FSA)
library(car)
library(forcats)
library(kableExtra) # nice Rmd tables
library(emmeans)
library(ggpubr)
```


#Larval Survival
```{r}
df<-read.csv("Data/larval_survival.csv", header = T) %>% 
  dplyr::mutate(Percent_Survival = as.numeric(Percent_Survival)) %>% 
  dplyr::select(-treatment) %>%  # redundant column with Exposure_OA
  
  # rename the variables for consistency using 'case_when'
  dplyr::mutate(Parental_OA = case_when(Parental_OA ==  "LOW" ~ "Low pCO2", 
                                        Parental_OA ==  "MODERATE" ~ "Moderate pCO2", 
                                        Parental_OA ==  "HIGH" ~ "High pCO2",
                                        Parental_OA ==  "WILD" ~ "None")) %>% 
  dplyr::mutate(Exposure_OA = case_when(Exposure_OA ==  "LOW" ~ "Low pCO2", 
                                        Exposure_OA ==  "MODERATE" ~ "Moderate pCO2", 
                                        Exposure_OA ==  "HIGH" ~ "High pCO2")) %>% 
  
  # change the levels for order when plotting - call as factors too!
  dplyr::mutate(Parental_OA = as.factor(forcats::fct_relevel(Parental_OA, c("Low pCO2", "Moderate pCO2", "High pCO2")))) %>% 
  dplyr::mutate(Exposure_OA = as.factor(forcats::fct_relevel(Exposure_OA, c("Low pCO2", "Moderate pCO2", "High pCO2")))) %>% 
  
  # rename them
  dplyr::rename(Parent_pCO2 = Parental_OA) %>% 
  dplyr::rename(Larvae_pCO2  = Exposure_OA) # done 
  
  
df$Percent_Survival_trans <- asin(sqrt(df$Percent_Survival))

head(df)
str(df)
```



```{r about data}

# number of runs 
unique(df$Generation) # 1, 2, and 3

Rep_Summary_all <- df %>% dplyr::select(c(Generation, Age, Parent_pCO2, Larvae_pCO2)) %>% 
                       dplyr::group_by_all() %>% 
                       dplyr::summarise(n=n())

# print the runs
# summary: 

Rep_Summary_G1 <- Rep_Summary_all %>%  dplyr::filter(Generation %in% 1) # for the other paper - full grow out multigenerational
Rep_Summary_G1 %>%  kbl() %>% kable_classic(full_width = F, html_font = "Cambria")

Rep_Summary_G2 <- Rep_Summary_all %>%  dplyr::filter(Generation %in% 2) # for the other paper - full grow out multigenerational
Rep_Summary_G2 %>%  kbl() %>% kable_classic(full_width = F, html_font = "Cambria")

Rep_Summary_G3 <- Rep_Summary_all %>%  dplyr::filter(Generation %in% 3) # for the other paper - full grow out multigenerational
Rep_Summary_G3 %>%  kbl() %>% kable_classic(full_width = F, html_font = "Cambria")

```


### make data frames for each generation
```{r}
df_F1 <- df%>%
  filter(Generation=="1")

df_F2 <- df%>%
  filter(Generation=="2")

df_F3 <- df%>%
  filter(Generation=="3")
```

# F1 Larval Survival
```{r}

stL <- summarySE(df_F1, measurevar="Percent_Survival", groupvars=c("Age", "Larvae_pCO2"))
stL 

ggplot(stL, aes(x=Age, y=Percent_Survival, color=Larvae_pCO2)) + geom_line()+
  geom_point()+ 
   geom_errorbar(aes(ymin=Percent_Survival-se, ymax=Percent_Survival+se), width=.2,
                position=position_dodge(.1)) +
  scale_color_manual(values=c("green4", "darkorange1", "purple"))+
  theme(legend.position="right", legend.direction="vertical", legend.title = element_blank())+ theme_bw() + 
  labs(x="Age (days)", y="Percent Survival")+ #scale_y_continuous(breaks=seq(0,100,20))+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))
 
```

# F2 Larval Survival
```{r}

stL <- summarySE(df_F2, measurevar="Percent_Survival", groupvars=c("Age", "Larvae_pCO2"))
stL 

ggplot(stL, aes(x=Age, y=Percent_Survival, color=Larvae_pCO2))+ geom_line()+
  geom_point()+ 
   geom_errorbar(aes(ymin=Percent_Survival-se, ymax=Percent_Survival+se), width=.2,
                position=position_dodge(.1)) +
  scale_color_manual(values=c("green4", "darkorange1", "purple"))+
  theme(legend.position="right", legend.direction="vertical", legend.title = element_blank())+ theme_bw() + 
  labs(x="Age (days)", y="Percent Survival")+ #scale_y_continuous(breaks=seq(0,100,20))+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))
 
```
# F3 Larval Survival
```{r}

stL <- summarySE(df_F3, measurevar="Percent_Survival", groupvars=c("Age", "Larvae_pCO2", "Parent_pCO2"))
stL 

Gen3_PlotMeanSE_All <- ggplot(stL, aes(x=Age, y=Percent_Survival, color=Larvae_pCO2))+ geom_line()+
                        geom_point()+ 
                         geom_errorbar(aes(ymin=Percent_Survival-se, ymax=Percent_Survival+se), width=.2,
                                      position=position_dodge(.1)) +
                        scale_color_manual(values=c("green4", "darkorange1", "purple"))+
                        theme(legend.position="right", legend.direction="vertical", legend.title = element_blank())+ theme_bw() + 
                        labs(x="Age (days)", y="Percent Survival")+ #scale_y_continuous(breaks=seq(0,100,20))+ 
                        theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))+
                        facet_wrap("Parent_pCO2")



# Summarise Percent Deformities for plotting 
Gen3_mean_survival <- df_F3 %>% 
                          dplyr::select(Parent_pCO2,Larvae_pCO2,Age, Percent_Survival) %>% 
                          na.omit() %>% 
                          dplyr::group_by(Age, Parent_pCO2,Larvae_pCO2) %>% 
                          dplyr::summarise(mean_Perc_surv = mean(Percent_Survival), 
                                           n           = n(),
                                           sd_Perc_surv   = sd(Percent_Survival),
                                           se_Perc_surv   = sd_Perc_surv/(sqrt(n)))

# Barplots 
unique(Gen3_mean_survival$Age)
Gen3_barplots_Age2 <- Gen3_mean_survival %>% dplyr::filter(Age ==2) %>% 
                        ggplot() +
                        geom_errorbar(aes(x=Larvae_pCO2, 
                                           ymin=mean_Perc_surv-se_Perc_surv, 
                                           ymax=mean_Perc_surv+se_Perc_surv), 
                                       width=0, # removes the horizontal line
                                       colour="black", 
                                       size=1) +
                        geom_bar(aes(x=Larvae_pCO2, y=mean_Perc_surv,fill=factor(Larvae_pCO2)), 
                                  stat="identity",
                                 width = 0.75,
                                 alpha = 0.5) +
                        labs(title="F3 Age 2 DPF - Perc Survival (Mean +- SE)", 
                            x ="pCO2 Offspring Exposure", 
                            y = "Percent Survival") +
                         scale_fill_manual(breaks=c("Low pCO2", "Moderate pCO2", "High pCO2"), 
                                             values=c("forestgreen","orange", "purple")) +
                        theme_classic() +
                        theme(panel.grid.major = element_blank(), 
                              panel.grid.minor = element_blank(), 
                              axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
                              axis.text=element_text(size=12),
                              legend.position="none") +
                        facet_wrap(~Parent_pCO2)
Gen3_barplots_Age5 <- Gen3_mean_survival %>% dplyr::filter(Age ==5) %>% 
                        ggplot() +
                        geom_errorbar(aes(x=Larvae_pCO2, 
                                           ymin=mean_Perc_surv-se_Perc_surv, 
                                           ymax=mean_Perc_surv+se_Perc_surv), 
                                       width=0, # removes the horizontal line
                                       colour="black", 
                                       size=1) +
                        geom_bar(aes(x=Larvae_pCO2, y=mean_Perc_surv,fill=factor(Larvae_pCO2)), 
                                  stat="identity",
                                 width = 0.75,
                                 alpha = 0.5) +
                        labs(title="F3 Age 5 DPF - Perc Survival (Mean +- SE)", 
                            x ="pCO2 Offspring Exposure", 
                            y = "Percent Survival") +
                         scale_fill_manual(breaks=c("Low pCO2", "Moderate pCO2", "High pCO2"), 
                                             values=c("forestgreen","orange", "purple")) +
                        theme_classic() +
                        theme(panel.grid.major = element_blank(), 
                              panel.grid.minor = element_blank(), 
                              axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
                              axis.text=element_text(size=12),
                              legend.position="none") +
                        facet_wrap(~Parent_pCO2)

Gen3_barplots_Age7 <- Gen3_mean_survival %>% dplyr::filter(Age ==7) %>% 
                        ggplot() +
                        geom_errorbar(aes(x=Larvae_pCO2, 
                                           ymin=mean_Perc_surv-se_Perc_surv, 
                                           ymax=mean_Perc_surv+se_Perc_surv), 
                                       width=0, # removes the horizontal line
                                       colour="black", 
                                       size=1) +
                        geom_bar(aes(x=Larvae_pCO2, y=mean_Perc_surv,fill=factor(Larvae_pCO2)), 
                                  stat="identity",
                                 width = 0.75,
                                 alpha = 0.5) +
                        labs(title="F3 Age 7 DPF - Perc Survival (Mean +- SE)", 
                            x ="pCO2 Offspring Exposure", 
                            y = "Percent Survival") +
                         scale_fill_manual(breaks=c("Low pCO2", "Moderate pCO2", "High pCO2"), 
                                             values=c("forestgreen","orange", "purple")) +
                        theme_classic() +
                        theme(panel.grid.major = element_blank(), 
                              panel.grid.minor = element_blank(), 
                              axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
                              axis.text=element_text(size=12),
                              legend.position="none") +
                        facet_wrap(~Parent_pCO2)

Gen3_barplots_Age12 <- Gen3_mean_survival %>% dplyr::filter(Age ==12) %>% 
                        ggplot() +
                        geom_errorbar(aes(x=Larvae_pCO2, 
                                           ymin=mean_Perc_surv-se_Perc_surv, 
                                           ymax=mean_Perc_surv+se_Perc_surv), 
                                       width=0, # removes the horizontal line
                                       colour="black", 
                                       size=1) +
                        geom_bar(aes(x=Larvae_pCO2, y=mean_Perc_surv,fill=factor(Larvae_pCO2)), 
                                  stat="identity",
                                 width = 0.75,
                                 alpha = 0.5) +
                        labs(title="F3 Age 12 DPF - Perc Survival (Mean +- SE)", 
                            x ="pCO2 Offspring Exposure", 
                            y = "Percent Survival") +
                         scale_fill_manual(breaks=c("Low pCO2", "Moderate pCO2", "High pCO2"), 
                                             values=c("forestgreen","orange", "purple")) +
                        theme_classic() +
                        theme(panel.grid.major = element_blank(), 
                              panel.grid.minor = element_blank(), 
                              axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
                              axis.text=element_text(size=12),
                              legend.position="none") +
                        facet_wrap(~Parent_pCO2)
Gen3_barplots_Age16 <- Gen3_mean_survival %>% dplyr::filter(Age ==16) %>% 
                        ggplot() +
                        geom_errorbar(aes(x=Larvae_pCO2, 
                                           ymin=mean_Perc_surv-se_Perc_surv, 
                                           ymax=mean_Perc_surv+se_Perc_surv), 
                                       width=0, # removes the horizontal line
                                       colour="black", 
                                       size=1) +
                        geom_bar(aes(x=Larvae_pCO2, y=mean_Perc_surv,fill=factor(Larvae_pCO2)), 
                                  stat="identity",
                                 width = 0.75,
                                 alpha = 0.5) +
                        labs(title="F3 Age 16 DPF - Perc Survival (Mean +- SE)", 
                            x ="pCO2 Offspring Exposure", 
                            y = "Percent Survival") +
                         scale_fill_manual(breaks=c("Low pCO2", "Moderate pCO2", "High pCO2"), 
                                             values=c("forestgreen","orange", "purple")) +
                        theme_classic() +
                        theme(panel.grid.major = element_blank(), 
                              panel.grid.minor = element_blank(), 
                              axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
                              axis.text=element_text(size=12),
                              legend.position="none") +
                        facet_wrap(~Parent_pCO2)

# print the plot

pdf("Output/Survival/PercSurvival_Gen3_All.pdf", width=10, height=5)
print(Gen3_PlotMeanSE_All)
dev.off()


pdf("Output/Survival/PercSurvival_Gen3_2DPF.pdf", width=5, height=5)
print(Gen3_barplots_Age2)
dev.off()

pdf("Output/Survival/PercSurvival_Gen3_5DPF.pdf", width=5, height=5)
print(Gen3_barplots_Age5)
dev.off()

pdf("Output/Survival/PercSurvival_Gen3_7DPF.pdf", width=5, height=5)
print(Gen3_barplots_Age7)
dev.off()

pdf("Output/Survival/PercSurvival_Gen3_12DPF.pdf", width=5, height=5)
print(Gen3_barplots_Age12)
dev.off()

pdf("Output/Survival/PercSurvival_Gen3_16DPF.pdf", width=5, height=5)
print(Gen3_barplots_Age16)
dev.off()

```

# Stats
Lenght data do not meet the assumptions of noramlity even with an asin(sqrt()) transformation
```{r}
leveneTest(Percent_Survival_trans ~ Larvae_pCO2, data=df_F1)
shapiro.test(df_F1$Percent_Survival_trans)

leveneTest(Percent_Survival_trans ~ Larvae_pCO2, data=df_F2)
shapiro.test(df_F2$Percent_Survival_trans)

leveneTest(Percent_Survival_trans ~ Larvae_pCO2, data=df_F3)
shapiro.test(df_F3$Percent_Survival_trans)
```

#Non parametric Stats
### F1 Survival
```{r}
scheirerRayHare(Percent_Survival ~ Larvae_pCO2*Age,
                data = df_F1)

dunnTest(Percent_Survival ~ Larvae_pCO2,
                data = df_F1,
              method="bh")

```

### F2 Survival
```{r}
scheirerRayHare(Percent_Survival ~ Larvae_pCO2*Age,
                data = df_F2)

res.kruskal <- kruskal.test(Percent_Survival ~ Larvae_pCO2, data = df_F2)
res.kruskal

```

### F3 Survival
```{r}


scheirerRayHare(Percent_Survival ~ Larvae_pCO2*Parent_pCO2,
                data = df_F3)

dunnTest(Percent_Survival ~ Larvae_pCO2,
                data = df_F3,
              method="bh")

dunnTest(Percent_Survival ~ Parent_pCO2,
                data = df_F3,
              method="bh")
```